pipelines:
  client:
    - or:
        - 'Test: '
        - \[endpoint:\(scClient
  server-0:
    - or:
        - \[endpoint:\(scServer/0
  server-1:
    - or:
        - \[endpoint:\(scServer/1
  server-2:
    - or:
        - \[endpoint:\(scServer/2
  trace:
    - or:
        - trace:\(scServer/1/34\)
  server-0-accept:
    - or:
        - accept
    - or:
        - \[endpoint:\(scServer/0
  apply-join:
    - or:
        - 'applyJoin: newNumOfGroups'
  num-28:
    - or:
        - Num:28
  apply-0:
    - or:
        - before applying
        - applying
        - after applying
    - or:
        - endpoint:\(scServer/0\)
  apply-1:
    - or:
        - before applying
        - applying
        - after applying
    - or:
        - endpoint:\(scServer/1\)
  apply-2:
    - or:
        - before applying
        - applying
        - after applying
    - or:
        - endpoint:\(scServer/2\)
  tests:
    - or:
        - 'Test: '